### PR TITLE
Document chunking-ng

### PR DESCRIPTION
**Pull request by ogoffart**

### CODE REVIEW

**Comment by ogoffart** [comment]
CC/ @moscicki @DeepDiver1975

**Comment by moscicki** [comment]
Thanks! It looks to me that assigning chunk numbers makes it impossible to change the chunk size dynamically for retries. So when you fail to upload chunk k, then you cannot split it in 2 chunks anymore if you decided to do so. Is it a problem?

**Comment by ogoffart** [comment]
> So when you fail to upload chunk k, then you cannot split it in 2 chunks anymore if you decided to do so. Is it a problem?

Well, you can, it just means you will have to re-upload all the chunks  after chunk k

**Comment by moscicki** [comment]
Well, "you can" but: is it a reasonable scheme to re-upload all the chunks after chunk k? It does not make sense to invalidate all existing uploads for a purpose of splitting a previous chunk in two. So practically speaking you cannot unless you accept to double the traffic for the rest of the file.

**Pull request merged**
