### PR TITLE
Fix error output, do not double decode file contents

### PR DESCRIPTION
**Pull request by PVince81**

### CODE REVIEW

**Comment by moscicki** [comment]
Does it lead to errors without your patch?

**Comment by PVince81** [comment]
Yes.
So far every time I ran the unicode jam test (with and without my patch), the tests fail.
And when they fail, they try and log output.

Without my fix: the error log output is broken due to encoding issues (fatal error)
With this fix: the error log output works correctly

**Comment by moscicki** [comment]
I am puzzled. It works for me. Python 2.6.6 / linux.

I will take a closer look. Could you please send me the output with the error? Which platform are you on?

**Comment by PVince81** [comment]
I have openSUSE Factory x86_64 with Python 2.7.9 and PHP 5.6.6

So far I didn't have any single unicode test that worked.
Here's an example output:

```
% bin/smash lib/test_unicodejam.py
SUMMARY:smash.:oc_server: 127.0.0.1
SUMMARY:smash.:oc_ssl_enabled: False
SUMMARY:smash.:runid: 150323-130500
SUMMARY:smash.:running lib/test_unicodejam.py in /home/vincent/work/smashdir/test_unicodejam as test testset #0 None
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
2015-03-23 13:05:10,319 - ERROR - worker1 - FILELEN: 81
2015-03-23 13:05:10,320 - ERROR - worker1 - FILE   : /home/vincent/work/smashdir/test_unicodejam/worker1/ğਅȗࢣω٠Ԯਬྰ༈ಟ഻࿳ວƌঘ͌યʝͮɖࡋ෷௱ಸఈࡘৄʹ
2015-03-23 13:05:10,320 - ERROR - worker1 - CONTENT: /home/vincent/work/smashdir/test_unicodejam/worker1/ğਅȗࢣω٠Ԯਬྰ༈ಟ഻࿳ວƌঘ͌યʝͮɖࡋ෷௱ಸఈࡘৄʹ
2015-03-23 13:05:10,320 - ERROR - worker1 - CONTLEN: 81
2015-03-23 13:05:10,321 - ERROR - worker1 - FILE    BYTES: u'/home/vincent/work/smashdir/test_unicodejam/worker1/\u011f\u0a05\u0217\u08a3\u03c9\u0660\u052e\u0a2c\u0fb0\u0f08\u0c9f\u0d3b\u0ff3\u0ea7\u018c\u0998\u034c\u0aaf\u029d\u036e\u0256\u084b\u0df7\u0bf1\u0cb8\u0c08\u0858\u09c4\u02b9' 229
2015-03-23 13:05:10,321 - ERROR - worker1 - CONTENT BYTES: u'/home/vincent/work/smashdir/test_unicodejam/worker1/\u011f\u0a05\u0217\u08a3\u03c9\u0660\u052e\u0a2c\u0fb0\u0f08\u0c9f\u0d3b\u0ff3\u0ea7\u018c\u0998\u034c\u0aaf\u029d\u036e\u0256\u084b\u0df7\u0bf1\u0cb8\u0c08\u0858\u09c4\u0374' 229
2015-03-23 13:05:10,321 - ERROR - worker1 - FILELEN: 63
2015-03-23 13:05:10,321 - ERROR - worker1 - FILE   : /home/vincent/work/smashdir/test_unicodejam/worker1/Ǐৣä࿃ಱٓȜ༦̈́Ϫ
2015-03-23 13:05:10,321 - ERROR - worker1 - CONTENT: /home/vincent/work/smashdir/test_unicodejam/worker1/Ǐৣä࿃ಱٓȜ༦̈́Ϫ
2015-03-23 13:05:10,321 - ERROR - worker1 - CONTLEN: 62
2015-03-23 13:05:10,321 - ERROR - worker1 - FILE    BYTES: u'/home/vincent/work/smashdir/test_unicodejam/worker1/\u01cf\u09e3\xe4\u0fc3\u0cb1\u0653\u021c\u0f26\u0308\u0301\u03ea' 119
2015-03-23 13:05:10,321 - ERROR - worker1 - CONTENT BYTES: u'/home/vincent/work/smashdir/test_unicodejam/worker1/\u01cf\u09e3\xe4\u0fc3\u0cb1\u0653\u021c\u0f26\u0344\u03ea' 113
2015-03-23 13:05:10,322 - ERROR - worker1 - FILELEN: 59
2015-03-23 13:05:10,322 - ERROR - worker1 - FILE   : /home/vincent/work/smashdir/test_unicodejam/worker1/Ӛ೨Ɓग़ܐ೚
2015-03-23 13:05:10,322 - ERROR - worker1 - CONTENT: /home/vincent/work/smashdir/test_unicodejam/worker1/Ӛ೨Ɓग़ܐ೚
2015-03-23 13:05:10,322 - ERROR - worker1 - CONTLEN: 58
2015-03-23 13:05:10,322 - ERROR - worker1 - FILE    BYTES: u'/home/vincent/work/smashdir/test_unicodejam/worker1/\u04da\u0ce8\u0181\u0917\u093c\u0710\u0cda' 97
2015-03-23 13:05:10,322 - ERROR - worker1 - CONTENT BYTES: u'/home/vincent/work/smashdir/test_unicodejam/worker1/\u04da\u0ce8\u0181\u095a\u0710\u0cda' 91
2015-03-23 13:05:10,323 - ERROR - worker1 - Not all files are OK! good=7, bad=3, expected=10
2015-03-23 13:05:10,323 - ERROR - worker1 - After synch corrupted files found: good=7, bad=3, expected=10
2015-03-23 13:05:11,327 - ERROR - worker1 - 2 error(s) reported
```

**Comment by PVince81** [comment]
Forgot to mention that I'm testing against OC master.
OC 8.0.2 has the same issues, running with mariadb 10.0.14

**Comment by moscicki** [comment]
Thanks for this contribution. I merged it already via the newer pull request.

**Pull request closed without merging**
