### PR TITLE
add short wait timer after every ocsync command and long wait after each retry

### PR DESCRIPTION
**Pull request by jcvicente**

### CODE REVIEW

**Comment by labkode** [comment]
@jcvicente what is the reason for the sleeps?

**Comment by jcvicente** [comment]
This is to avoid the race condition between syncs of different workers in the basicSync test and allow the test to run smoothly without failed syncs due to timeouts on consecutive retries (i.e. having the file that is modified by both the winner and the loser modified last by the loser and ending up with an "inconsistent checksum" error because of that, having missing files in the checker, etc...)

**Comment by labkode** [comment]
@jcvicente I see now. Let's see then if we get the same errors.

**Comment by jcvicente** [comment]
most of them disappeared already :)

**Pull request merged**
