### PR TITLE
specify that we want python2

### PR DESCRIPTION
**Pull request by MorrisJobke**
@icewind1991 ported the cernbox to be compliant with python3 default machines.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @moscicki ;)

**Comment by moscicki** [comment]
@MorrisJobke: thanks!

I see a problem in MacOSX: there is no python2 executable. There is python, python2.7 etc.
Actually I don't know what is  the best way of handling this. Any ideas?

**Comment by MorrisJobke** [comment]
> I see a problem in MacOSX: there is no python2 executable. There is python, python2.7 etc.
> Actually I don't know what is the best way of handling this. Any ideas?

Damn :( I just know it from my linux box, where there are several symlinks to these versions:

```
lrwxrwxrwx  1 root root             7 25. Mär 18:30 python -> python3
lrwxrwxrwx  1 root root             9 11. Dez 05:51 python2 -> python2.7
-rwxr-xr-x  1 root root          6224 11. Dez 05:51 python2.7
lrwxrwxrwx  1 root root             9 25. Mär 18:30 python3 -> python3.4
-rwxr-xr-x  2 root root         10440 25. Mär 18:30 python3.4
```

So python2.7 should work too. @icewind1991 Ideas?

**Comment by MorrisJobke** [comment]
@moscicki Sorry for the delay. I updated the python2 version to python2.7.

**Comment by MorrisJobke** [comment]
Rebased to satisfy travis :)

**Comment by moscicki** [comment]
Specifying 2.7 is even worse -- I have only 2.6 on redhat6. But OK, if that solves the problem for someone with python3 installed we can go back to the original idea of specifying python2. Then I will patch my MacOSX environment... I will handle this pull request later.

**Comment by MorrisJobke** [comment]
> Specifying 2.7 is even worse -- I have only 2.6 on redhat6. But OK, if that solves the problem for someone with python3 installed we can go back to the original idea of specifying python2. Then I will patch my MacOSX environment... I will handle this pull request later.

Thanks. We definetely need to specify this, because other distros will also switch to python3 in the future and then we experience even more problems.

**Comment by moscicki** [comment]
Sorry @MorrisJobke: could you please go back to specifying python2 everywhere instead of python2.7. Out of these two suboptimal options 2.7 is much more suboptimal. Thanks!

**Comment by MorrisJobke** [comment]
No problem :) Will do this tomorrow morning :)

**Comment by MorrisJobke** [comment]
> Sorry @MorrisJobke: could you please go back to specifying python2 everywhere instead of python2.7. Out of these two suboptimal options 2.7 is much more suboptimal. Thanks!

Done :)

**Comment by moscicki** [comment]
Thanks!

**Comment by MorrisJobke** [comment]
> Thanks!

Thank you for accepting upstream :)

**Pull request merged**
